### ISSUE TITLE
Error compiling for board Arduino/Genuino Uno

### ISSUE THREAD

**Issue by leevawns** [mattairtech/SRAM_23LC#1]
hi ! i have a problem with library, do you can help me pls !

![image](https://user-images.githubusercontent.com/29629493/27435114-3ffc6cc8-5785-11e7-8b4c-51f13830d436.png)

i use arduino uno,IDE 1.6,  run example from library

error with #include "wiring_digital.h"     compilation terminated.

**Comment by mattairtech** [comment]
This has been fixed in https://github.com/mattairtech/SRAM_23LC/commit/cd5e6099fb5675cb87a05714104e4f7794aa57d9.
An update should be available within Library Manager very soon.
