### ISSUE TITLE
Arduino Mega

### ISSUE THREAD

**Issue by mataide** [mattairtech/SRAM_23LC#2]
This library works for arduino mega?

I just receive: 

Write Block:
Write Block Failure
Read Byte:
Write Byte:
Read Block: Read Block Failure

My connections are:
![arduino-sram-schematic](https://user-images.githubusercontent.com/28991236/31392894-c4ec111e-adb0-11e7-92c8-dcedaa06e256.png)

**Comment by AlexTanTK** [comment]
I have tried the library on Arduino UNO and encounter the same issue.

I solve my issue by changing the type declaration in file SRAM_23LC.h
Line 128 from "size_t _capacity;" to "uint32_t _capacity;"

Note: There is an increase in bytes used for this fixed. Therefore take caution for memory management.

Alex Tan TK
Rectify Engineering
Singapore

**Comment by peterpar** [comment]
It would be good to update the source with this fix since it works and its compatible with the rest of the code where the passed in address value is 32bit. It would save a lot of people a lot of time ;-)

**Comment by mhaag1** [comment]
I cant event write a byte to the IC, using a 23LCV1024 with a Adafruit M0 Express(SAMD21 chip) in Arduino IDE...tried writing a byte to a specific address and then reading the address to see if the byte was written to it correctly, but all I get is a zero(0)...Everything is hooked up correctly.

**Comment by mattairtech** [comment]
Sorry this took so long. I missed the notification and I have not used Github for some time now.
